## Import library, load data and select useful columns

In [1]:
#import library

import pandas as pd
#load dataset
df = pd.read_csv('Crashes_Last_Five_Years.csv')
#filter by rural accidents
df=df[df['STAT_DIV_NAME'] == 'Country'] 
#drop unwanted columns
df.drop(['LATITUDE', 'LONGITUDE','OBJECTID','ABS_CODE', 'ACCIDENT_STATUS','VICGRID_X','VICGRID_Y', 'SRNS', 'SRNS_ALL','DIVIDED', 'DIVIDED_ALL', 'UNKNOWN', 'LGA_NAME_ALL'], axis=1, inplace=True)
print(df.columns)
print(df.shape)

Index(['X', 'Y', 'ACCIDENT_NO', 'ACCIDENT_DATE', 'ACCIDENT_TIME',
       'ALCOHOLTIME', 'ACCIDENT_TYPE', 'DAY_OF_WEEK', 'DCA_CODE',
       'HIT_RUN_FLAG', 'LIGHT_CONDITION', 'POLICE_ATTEND', 'ROAD_GEOMETRY',
       'SEVERITY', 'SPEED_ZONE', 'RUN_OFFROAD', 'NODE_ID', 'NODE_TYPE',
       'LGA_NAME', 'REGION_NAME', 'TOTAL_PERSONS', 'INJ_OR_FATAL', 'FATALITY',
       'SERIOUSINJURY', 'OTHERINJURY', 'NONINJURED', 'MALES', 'FEMALES',
       'BICYCLIST', 'PASSENGER', 'DRIVER', 'PEDESTRIAN', 'PILLION', 'MOTORIST',
       'PED_CYCLIST_5_12', 'PED_CYCLIST_13_18', 'OLD_PEDESTRIAN', 'OLD_DRIVER',
       'YOUNG_DRIVER', 'ALCOHOL_RELATED', 'UNLICENCSED', 'NO_OF_VEHICLES',
       'HEAVYVEHICLE', 'PASSENGERVEHICLE', 'MOTORCYCLE', 'PUBLICVEHICLE',
       'DEG_URBAN_NAME', 'DEG_URBAN_ALL', 'REGION_NAME_ALL', 'RMA', 'RMA_ALL',
       'STAT_DIV_NAME'],
      dtype='object')
(21651, 52)

## The dataset doesn't have LGA
#### load ACCIDENT_LOCATION.csv 
#### merge the two

In [2]:
#merge the above with accident location to get LGA column
ACCIDENT_LOCATION = pd.read_csv('ACCIDENT/ACCIDENT_LOCATION.csv', usecols=['ACCIDENT_NO','ROAD_NAME', 'ROAD_TYPE' ])
df1 = pd.merge(df, ACCIDENT_LOCATION, on = "ACCIDENT_NO")
df1.shape
#concatenate road_name and road_type. Name it ROAD
df1['ROAD'] = df1['ROAD_NAME'] + " " + df1['ROAD_TYPE']
df1.shape
df1

,X,Y,ACCIDENT_NO,ACCIDENT_DATE,ACCIDENT_TIME,ALCOHOLTIME,ACCIDENT_TYPE,DAY_OF_WEEK,DCA_CODE,HIT_RUN_FLAG,...,PUBLICVEHICLE,DEG_URBAN_NAME,DEG_URBAN_ALL,REGION_NAME_ALL,RMA,RMA_ALL,STAT_DIV_NAME,ROAD_NAME,ROAD_TYPE,ROAD
0,145.944658,-36.540203,T20130026788,28/12/2013,01.30.00,Yes,Collision with a fixed object,Saturday,OFF LEFT BEND INTO OBJECT/PARKED VEHICLE,Yes,...,0,RURAL_VICTORIA,RURAL_VICTORIA,NORTH EASTERN REGION,Local Road,Local Road,Country,GOOMALIBEE,ROAD,GOOMALIBEE ROAD
1,144.170790,-36.915629,T20130026801,29/12/2013,12.50.00,No,Collision with a fixed object,Sunday,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,No,...,0,RURAL_VICTORIA,RURAL_VICTORIA,NORTHERN REGION,Local Road,Local Road,Country,HOKINS,ROAD,HOKINS ROAD
2,144.341675,-38.073042,T20130026807,29/12/2013,14.35.00,No,Collision with a fixed object,Sunday,OFF RIGHT BEND INTO OBJECT/PARKED VEHICLE,No,...,0,LARGE_PROVINCIAL_CITIES,LARGE_PROVINCIAL_CITIES,SOUTH WESTERN REGION,Local Road,Local Road,Country,LEWIS,PLACE,LEWIS PLACE
3,146.479006,-38.200890,T20130025565,11/12/2013,15.59.00,No,Collision with vehicle,Wednesday,RIGHT NEAR (INTERSECTIONS ONLY),No,...,0,RURAL_VICTORIA,RURAL_VICTORIA,"EASTERN REGION,EASTERN REGION",Local Road,Local Road,Country,OLD MELBOURNE,ROAD,OLD MELBOURNE ROAD
4,144.086782,-37.106458,T20130025572,11/12/2013,17.40.00,No,Collision with a fixed object,Wednesday,RIGHT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,No,...,0,RURAL_VICTORIA,RURAL_VICTORIA,NORTHERN REGION,Arterial Highway,Arterial Highway,Country,PYRENEES,HIGHWAY,PYRENEES HIGHWAY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21645,147.270543,-36.850920,T20190001365,23/1/2019,14.25.00,No,Collision with vehicle,Wednesday,HEAD ON (NOT OVERTAKING),No,...,0,RURAL_VICTORIA,RURAL_VICTORIA,NORTH EASTERN REGION,Arterial Other,Arterial Other,Country,BOGONG HIGH PLAINS,ROAD,BOGONG HIGH PLAINS ROAD
21646,145.412564,-36.368053,T20190001373,23/1/2019,17.55.00,No,Collision with vehicle,Tuesday,RIGHT REAR.,No,...,0,SMALL_CITIES,SMALL_CITIES,NORTH EASTERN REGION,Arterial Other,"Arterial Other,Local Road",Country,BALACLAVA,ROAD,BALACLAVA ROAD
21647,145.886563,-37.167491,T20190001944,26/1/2019,16.00.00,Yes,Vehicle overturned (no collision),Friday,OUT OF CONTROL ON CARRIAGEWAY (ON BEND),No,...,0,RURAL_VICTORIA,RURAL_VICTORIA,NORTH EASTERN REGION,Local Road,Local Road,Country,PLANTATION,ROAD,PLANTATION ROAD
21648,146.279172,-38.329167,T20190001958,29/1/2019,12.00.00,No,Collision with a fixed object,Tuesday,OFF LEFT BEND INTO OBJECT/PARKED VEHICLE,No,...,0,RURAL_VICTORIA,RURAL_VICTORIA,"EASTERN REGION,EASTERN REGION",Local Road,Local Road,Country,CREAMERY,ROAD,CREAMERY ROAD
21649,147.059224,-38.025143,T20190001981,1/2/2019,18.44.00,Yes,Collision with a fixed object,Friday,PERMANENT OBSTRUCTION ON CARRIAGEWAY,No,...,0,RURAL_VICTORIA,RURAL_VICTORIA,"EASTERN REGION,EASTERN REGION",Arterial Highway,Arterial Highway,Country,PRINCES,HIGHWAY,PRINCES HIGHWAY

## Group by LGA and write to csv

In [3]:
#groupby LGA_NAME and then group by Road
groupbyLGA = df1.groupby(['LGA_NAME', 'ROAD'])
groupbyLGA = groupbyLGA['ACCIDENT_NO'].count()
#the above is now a series, convert to df
groupbyLGA=groupbyLGA.to_frame()
groupbyLGA.to_csv("aggregated_data.csv", encoding="utf-8")
groupbyLGA['ACCIDENT_NO'].sort_values

<bound method Series.sort_values of LGA_NAME         ROAD
                                                19
(FALLS CREEK)    BOGONG HIGH PLAINS ROAD        13
                 FALLS CREEK ROAD                1
                 SCHUSS STREET                   1
(FRENCH ISLAND)  TANKERTON ROAD                  1
                                                ..
YARRIAMBIACK     PATCHEWOLLOCK-SEA LAKE ROAD     1
                 SCOTT STREET                    1
                 STAWELL-WARRACKNABEAL ROAD      6
                 SUNRAYSIA HIGHWAY               6
                 WIMMERA HIGHWAY                 2
Name: ACCIDENT_NO, Length: 6423, dtype: int64>

In [4]:
df3 = pd.read_csv('ACCIDENT/ACCIDENT_LOCATION.csv')
df3

,ACCIDENT_NO,NODE_ID,ROAD_ROUTE_1,ROAD_NAME,ROAD_TYPE,ROAD_NAME_INT,ROAD_TYPE_INT,DISTANCE_LOCATION,DIRECTION_LOCATION,NEAREST_KM_POST,OFF_ROAD_LOCATION
0,T20060000010,43078,2090.0,FOSTER,STREET,MCCRAE,STREET,0.0,SW,NaN,NaN
1,T20060000018,29720,5057.0,HALLAM,ROAD,BELGRAVE-HALLAM,ROAD,70.0,S,NaN,NaN
2,T20060000022,203074,9999.0,BROWNS,ROAD,TRUEMANS,ROAD,210.0,W,NaN,NaN
3,T20060000023,55462,2400.0,SPRINGVALE,ROAD,KEYSBOROUGH,AVENUE,0.0,N,NaN,NaN
4,T20060000026,202988,9999.0,ELIZABETH,AVENUE,GREENHOOD,CRESCENT,20.0,N,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
186541,T20190026313,613312,9999.0,SOMERVILLE,ROAD,KADINA,COURT,76.0,SW,NaN,NaN
186542,T20190026321,613591,9999.0,TILBURN,ROAD,WESTERN RING,ROAD,15.0,W,NaN,NaN
186543,T20190026322,278926,5421.0,ROBINSONS,ROAD,ROBINSONS-WESTERN OUT ON,RAMP,0.0,S,NaN,NaN
186544,T20190026336,38154,5744.0,WATERDALE,ROAD,ST HELLIER,STREET,0.0,S,NaN,NaN
186545,T20190026346,613592,9999.0,ST GEORGES,ROAD,ALEXANDRA,AVENUE,8.0,E,NaN,NaN

In [5]:
df4 = pd.read_csv('ACCIDENT/NODE.csv',usecols=['ACCIDENT_NO','Postcode No'])
df4

         ACCIDENT_NO  Postcode No
0       T20060000010         3175
1       T20060000018         3804
2       T20060000022         3939
3       T20060000023         3173
4       T20060000026         3940
...              ...          ...
188594  T20190026313         3551
188595  T20190026321         3023
188596  T20190026322         3029
188597  T20190026336         3081
188598  T20190026346         3142

[188599 rows x 2 columns]

In [6]:
df2 = pd.merge(df1, df4, on = "ACCIDENT_NO")
df2

,X,Y,ACCIDENT_NO,ACCIDENT_DATE,ACCIDENT_TIME,ALCOHOLTIME,ACCIDENT_TYPE,DAY_OF_WEEK,DCA_CODE,HIT_RUN_FLAG,...,DEG_URBAN_NAME,DEG_URBAN_ALL,REGION_NAME_ALL,RMA,RMA_ALL,STAT_DIV_NAME,ROAD_NAME,ROAD_TYPE,ROAD,Postcode No
0,145.944658,-36.540203,T20130026788,28/12/2013,01.30.00,Yes,Collision with a fixed object,Saturday,OFF LEFT BEND INTO OBJECT/PARKED VEHICLE,Yes,...,RURAL_VICTORIA,RURAL_VICTORIA,NORTH EASTERN REGION,Local Road,Local Road,Country,GOOMALIBEE,ROAD,GOOMALIBEE ROAD,3672
1,144.170790,-36.915629,T20130026801,29/12/2013,12.50.00,No,Collision with a fixed object,Sunday,LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,No,...,RURAL_VICTORIA,RURAL_VICTORIA,NORTHERN REGION,Local Road,Local Road,Country,HOKINS,ROAD,HOKINS ROAD,3453
2,144.341675,-38.073042,T20130026807,29/12/2013,14.35.00,No,Collision with a fixed object,Sunday,OFF RIGHT BEND INTO OBJECT/PARKED VEHICLE,No,...,LARGE_PROVINCIAL_CITIES,LARGE_PROVINCIAL_CITIES,SOUTH WESTERN REGION,Local Road,Local Road,Country,LEWIS,PLACE,LEWIS PLACE,3214
3,146.479006,-38.200890,T20130025565,11/12/2013,15.59.00,No,Collision with vehicle,Wednesday,RIGHT NEAR (INTERSECTIONS ONLY),No,...,RURAL_VICTORIA,RURAL_VICTORIA,"EASTERN REGION,EASTERN REGION",Local Road,Local Road,Country,OLD MELBOURNE,ROAD,OLD MELBOURNE ROAD,3840
4,144.086782,-37.106458,T20130025572,11/12/2013,17.40.00,No,Collision with a fixed object,Wednesday,RIGHT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICLE,No,...,RURAL_VICTORIA,RURAL_VICTORIA,NORTHERN REGION,Arterial Highway,Arterial Highway,Country,PYRENEES,HIGHWAY,PYRENEES HIGHWAY,3462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21917,147.270543,-36.850920,T20190001365,23/1/2019,14.25.00,No,Collision with vehicle,Wednesday,HEAD ON (NOT OVERTAKING),No,...,RURAL_VICTORIA,RURAL_VICTORIA,NORTH EASTERN REGION,Arterial Other,Arterial Other,Country,BOGONG HIGH PLAINS,ROAD,BOGONG HIGH PLAINS ROAD,3699
21918,145.412564,-36.368053,T20190001373,23/1/2019,17.55.00,No,Collision with vehicle,Tuesday,RIGHT REAR.,No,...,SMALL_CITIES,SMALL_CITIES,NORTH EASTERN REGION,Arterial Other,"Arterial Other,Local Road",Country,BALACLAVA,ROAD,BALACLAVA ROAD,3630
21919,145.886563,-37.167491,T20190001944,26/1/2019,16.00.00,Yes,Vehicle overturned (no collision),Friday,OUT OF CONTROL ON CARRIAGEWAY (ON BEND),No,...,RURAL_VICTORIA,RURAL_VICTORIA,NORTH EASTERN REGION,Local Road,Local Road,Country,PLANTATION,ROAD,PLANTATION ROAD,3713
21920,146.279172,-38.329167,T20190001958,29/1/2019,12.00.00,No,Collision with a fixed object,Tuesday,OFF LEFT BEND INTO OBJECT/PARKED VEHICLE,No,...,RURAL_VICTORIA,RURAL_VICTORIA,"EASTERN REGION,EASTERN REGION",Local Road,Local Road,Country,CREAMERY,ROAD,CREAMERY ROAD,3871
21921,147.059224,-38.025143,T20190001981,1/2/2019,18.44.00,Yes,Collision with a fixed object,Friday,PERMANENT OBSTRUCTION ON CARRIAGEWAY,No,...,RURAL_VICTORIA,RURAL_VICTORIA,"EASTERN REGION,EASTERN REGION",Arterial Highway,Arterial Highway,Country,PRINCES,HIGHWAY,PRINCES HIGHWAY,3851

In [7]:
centroidStuff = df2.filter(['X','Y','ROAD','Postcode No','ACCIDENT_NO'])
centroidStuff

,X,Y,ROAD,Postcode No,ACCIDENT_NO
0,145.944658,-36.540203,GOOMALIBEE ROAD,3672,T20130026788
1,144.170790,-36.915629,HOKINS ROAD,3453,T20130026801
2,144.341675,-38.073042,LEWIS PLACE,3214,T20130026807
3,146.479006,-38.200890,OLD MELBOURNE ROAD,3840,T20130025565
4,144.086782,-37.106458,PYRENEES HIGHWAY,3462,T20130025572
...,...,...,...,...,...
21917,147.270543,-36.850920,BOGONG HIGH PLAINS ROAD,3699,T20190001365
21918,145.412564,-36.368053,BALACLAVA ROAD,3630,T20190001373
21919,145.886563,-37.167491,PLANTATION ROAD,3713,T20190001944
21920,146.279172,-38.329167,CREAMERY ROAD,3871,T20190001958
21921,147.059224,-38.025143,PRINCES HIGHWAY,3851,T20190001981

In [8]:
newStuff = centroidStuff[centroidStuff['Postcode No'] == 3211]
newStuff[newStuff['ROAD'] == 'BACCHUS MARSH ROAD' ]

                X          Y                ROAD  Postcode No   ACCIDENT_NO
15628  144.359806 -37.934559  BACCHUS MARSH ROAD         3211  T20170014075

In [32]:
newDF = centroidStuff.groupby(['Postcode No', 'ROAD'])['X','Y'].median()
newDF

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

                                                     X          Y
Postcode No ROAD
3211        BACCHUS MARSH ROAD              144.359806 -37.934559
            BRANCH ROAD                     144.406502 -37.965321
            FARRARS ROAD                    144.462483 -37.966730
            GEELONG-BACCHUS MARSH ROAD      144.351980 -37.956230
            GIFKINS ROAD                    144.452060 -37.911250
...                                                ...        ...
3996        RAMSEY BOULEVARD -VENUS STREET  145.726109 -38.638068
            TOORAK ROAD                     145.701221 -38.642042
            WILLIAMS STREET                 145.729823 -38.632261
            WILLIAMS STREET SERVICE ROAD    145.730649 -38.627887
            WONTHAGGI ROAD                  145.721736 -38.627019

[7450 rows x 2 columns]

In [10]:
newDF.to_csv("aggregated_coordinates.csv", encoding="utf-8")

In [11]:
newDF.to_csv("aggregated_coordinates.csv", encoding="utf-8")

In [33]:
newerDF = centroidStuff.groupby(['Postcode No', 'ROAD'])['ACCIDENT_NO'].count()
newerDF

Postcode No  ROAD
3211         BACCHUS MARSH ROAD                1
             BRANCH ROAD                       1
             FARRARS ROAD                      2
             GEELONG-BACCHUS MARSH ROAD        1
             GIFKINS ROAD                      1
                                              ..
3996         RAMSEY BOULEVARD -VENUS STREET    1
             TOORAK ROAD                       1
             WILLIAMS STREET                   2
             WILLIAMS STREET SERVICE ROAD      1
             WONTHAGGI ROAD                    5
Name: ACCIDENT_NO, Length: 7450, dtype: int64

In [13]:
newerDF

Postcode No  ROAD
3211         BACCHUS MARSH ROAD                1
             BRANCH ROAD                       1
             FARRARS ROAD                      2
             GEELONG-BACCHUS MARSH ROAD        1
             GIFKINS ROAD                      1
                                              ..
3996         RAMSEY BOULEVARD -VENUS STREET    1
             TOORAK ROAD                       1
             WILLIAMS STREET                   2
             WILLIAMS STREET SERVICE ROAD      1
             WONTHAGGI ROAD                    5
Name: ACCIDENT_NO, Length: 7450, dtype: int64

In [34]:
final = pd.merge(newDF, newerDF, on = ["Postcode No","ROAD"])

In [15]:
newDF

                                                     X          Y
Postcode No ROAD
3211        BACCHUS MARSH ROAD              144.359806 -37.934559
            BRANCH ROAD                     144.406502 -37.965321
            FARRARS ROAD                    144.462483 -37.966730
            GEELONG-BACCHUS MARSH ROAD      144.351980 -37.956230
            GIFKINS ROAD                    144.452060 -37.911250
...                                                ...        ...
3996        RAMSEY BOULEVARD -VENUS STREET  145.726109 -38.638068
            TOORAK ROAD                     145.701221 -38.642042
            WILLIAMS STREET                 145.729823 -38.632261
            WILLIAMS STREET SERVICE ROAD    145.730649 -38.627887
            WONTHAGGI ROAD                  145.721736 -38.627019

[7450 rows x 2 columns]

In [16]:
final["ACCIDENT_NO"].sort_values(ascending=False)

Postcode No  ROAD
3214         PRINCES HIGHWAY          121
3350         STURT STREET             102
3555         HIGH STREET               90
3214         THOMPSON ROAD             77
3280         RAGLAN PARADE             72
                                     ...
3629         MADGE COURT                1
             MCFARLANE ROAD             1
             MCILROY ROAD               1
             MERRIGUM-ARDMONA ROAD      1
3211         BACCHUS MARSH ROAD         1
Name: ACCIDENT_NO, Length: 7450, dtype: int64

In [17]:
final.to_csv("AccidentLocation.csv", encoding="utf-8")

In [18]:
addingStuff = pd.merge(centroidStuff, final, on= ["Postcode No","ROAD"])
addingStuff

,X_x,Y_x,ROAD,Postcode No,ACCIDENT_NO_x,X_y,Y_y,ACCIDENT_NO_y
0,145.944658,-36.540203,GOOMALIBEE ROAD,3672,T20130026788,145.943340,-36.537342,4
1,145.939989,-36.533380,GOOMALIBEE ROAD,3672,T20130022053,145.943340,-36.537342,4
2,145.948315,-36.540773,GOOMALIBEE ROAD,3672,T20140002530,145.943340,-36.537342,4
3,145.940396,-36.535011,GOOMALIBEE ROAD,3672,T20140021930,145.943340,-36.537342,4
4,144.170790,-36.915629,HOKINS ROAD,3453,T20130026801,144.170790,-36.915629,1
...,...,...,...,...,...,...,...,...
21721,143.086229,-38.584323,MELROSE ROAD,3268,T20190001310,143.086229,-38.584323,1
21722,143.862660,-37.564229,LITTLE CHANNEL STREET,3350,T20190001879,143.862660,-37.564229,1
21723,144.280407,-36.783986,PATERSON STREET,3550,T20190003163,144.280407,-36.783986,1
21724,146.638740,-36.027811,BARNAWARTHA ROAD,3685,T20190001335,146.638740,-36.027811,1
21725,142.522492,-37.884512,GLENTHOMPSON-CARAMUT ROAD,3274,T20190001355,142.522492,-37.884512,1

In [19]:
from math import radians, sin, cos, asin, sqrt
def haversine(lon1, lat1, lon2, lat2):
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    return 2 * 6371 * asin(sqrt(a))

In [35]:
CentDist = [round(haversine(row.X_x,row.Y_x,row.X_y,row.Y_y),3) for index, row in addingStuff.iterrows()]
CentDist

[0.339,
 0.533,
 0.586,
 0.369,
 0.0,
 0.0,
 1.387,
 1.387,
 0.289,
 0.718,
 1.462,
 1.413,
 0.384,
 1.424,
 0.617,
 0.742,
 2.683,
 3.152,
 5.093,
 1.133,
 2.751,
 3.407,
 0.026,
 0.026,
 1.365,
 0.672,
 0.115,
 0.409,
 0.858,
 0.892,
 0.25,
 0.739,
 0.404,
 0.568,
 0.589,
 0.568,
 0.568,
 1.207,
 0.858,
 0.739,
 0.963,
 3.338,
 5.457,
 2.444,
 5.206,
 2.217,
 0.853,
 1.245,
 5.528,
 2.978,
 1.376,
 2.151,
 2.908,
 2.539,
 2.934,
 3.969,
 2.77,
 1.28,
 3.536,
 2.413,
 3.376,
 4.765,
 4.915,
 2.372,
 1.241,
 1.62,
 0.898,
 0.91,
 0.725,
 0.701,
 3.171,
 0.44,
 4.584,
 0.329,
 1.093,
 0.01,
 0.347,
 1.093,
 0.221,
 0.33,
 1.634,
 0.347,
 1.093,
 0.01,
 0.347,
 0.01,
 0.01,
 0.118,
 0.118,
 0.952,
 0.561,
 0.248,
 0.01,
 1.093,
 1.093,
 0.561,
 0.347,
 0.347,
 1.328,
 0.015,
 0.142,
 1.219,
 0.01,
 0.347,
 0.0,
 0.062,
 0.065,
 0.222,
 0.35,
 0.062,
 0.188,
 0.402,
 0.188,
 0.406,
 0.065,
 2.085,
 3.707,
 9.228,
 7.37,
 10.558,
 4.12,
 10.187,
 5.729,
 9.228,
 10.47,
 2.416,
 10.102,
 7.812,
 0.0,
 0.433,
 0.343,
 0.949,
 0.05,
 0.616,
 0.25,
 0.574,
 0.822,
 0.881,
 0.169,
 0.343,
 0.645,
 0.169,
 0.169,
 0.169,
 0.613,
 0.25,
 0.163,
 0.21,
 0.103,
 0.324,
 0.574,
 0.103,
 0.29,
 0.324,
 0.324,
 0.103,
 0.324,
 0.714,
 1.364,
 0.574,
 0.101,
 0.097,
 0.103,
 0.103,
 0.304,
 0.103,
 0.0,
 13.963,
 13.918,
 10.596,
 14.433,
 23.431,
 7.191,
 21.782,
 22.678,
 25.466,
 11.303,
 20.926,
 16.913,
 29.702,
 40.031,
 0.0,
 4.464,
 5.349,
 9.259,
 5.332,
 5.074,
 6.977,
 6.437,
 3.916,
 4.695,
 6.988,
 15.629,
 10.341,
 21.523,
 4.996,
 13.373,
 20.542,
 0.0,
 5.608,
 6.842,
 7.081,
 0.616,
 1.201,
 2.796,
 1.589,
 2.743,
 2.202,
 7.341,
 6.885,
 1.532,
 4.993,
 4.014,
 4.086,
 4.227,
 2.054,
 3.88,
 4.047,
 1.791,
 3.232,
 0.896,
 10.368,
 5.005,
 10.193,
 7.36,
 2.054,
 13.465,
 9.033,
 3.836,
 1.447,
 10.612,
 2.189,
 1.774,
 0.929,
 0.25,
 2.137,
 2.834,
 1.212,
 0.184,
 0.086,
 0.059,
 0.216,
 1.237,
 0.189,
 0.669,
 1.264,
 1.208,
 1.118,
 1.198,
 0.229,
 0.49,
 0.224,
 0.229,
 0.218,
 0.219,
 0.63,
 0.532,
 0.246,
 0.189,
 2.277,
 0.299,
 1.354,
 2.036,
 0.231,
 0.269,
 1.012,
 19.821,
 5.689,
 17.322,
 12.847,
 18.68,
 12.724,
 18.325,
 12.546,
 9.788,
 13.197,
 19.356,
 12.592,
 9.593,
 35.592,
 19.961,
 18.081,
 19.459,
 18.892,
 13.758,
 12.461,
 20.089,
 19.459,
 23.018,
 0.379,
 0.532,
 0.379,
 4.094,
 2.619,
 0.368,
 0.764,
 0.764,
 5.8,
 0.483,
 0.5,
 0.762,
 0.764,
 0.764,
 0.762,
 5.8,
 0.764,
 0.483,
 0.556,
 0.49,
 0.352,
 0.187,
 0.764,
 0.265,
 0.171,
 0.171,
 0.613,
 0.137,
 0.171,
 0.596,
 1.195,
 0.137,
 0.483,
 0.137,
 0.19,
 0.764,
 0.764,
 0.596,
 0.525,
 0.491,
 1.904,
 1.904,
 0.209,
 1.571,
 1.868,
 1.392,
 1.567,
 0.17,
 0.141,
 0.098,
 0.285,
 2.93,
 2.128,
 6.325,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.7,
 3.7,
 1.201,
 1.04,
 0.161,
 0.972,
 0.972,
 0.175,
 0.175,
 6.052,
 1.568,
 4.083,
 3.267,
 2.122,
 6.623,
 1.694,
 5.076,
 1.998,
 4.937,
 3.262,
 16.541,
 5.512,
 1.75,
 3.262,
 9.126,
 3.262,
 3.896,
 1.422,
 2.783,
 5.199,
 6.046,
 2.915,
 2.783,
 2.783,
 2.783,
 2.783,
 2.783,
 2.783,
 2.808,
 3.183,
 5.809,
 3.174,
 1.275,
 3.529,
 4.807,
 4.665,
 4.313,
 1.911,
 0.633,
 2.05,
 3.02,
 7.29,
 0.838,
 2.924,
 0.126,
 1.257,
 0.986,
 0.986,
 1.626,
 1.626,
 0.344,
 0.749,
 1.127,
 1.605,
 0.492,
 0.344,
 0.344,
 0.241,
 0.295,
 0.986,
 0.986,
 0.906,
 1.605,
 0.344,
 0.986,
 0.986,
 0.408,
 0.295,
 0.344,
 0.978,
 1.605,
 0.295,
 0.104,
 0.391,
 0.0,
 8.494,
 6.933,
 5.927,
 3.687,
 5.107,
 4.188,
 8.058,
 3.272,
 13.769,
 33.982,
 11.611,
 1.174,
 5.927,
 1.835,
 1.504,
 0.892,
 0.291,
 0.139,
 2.514,
 0.838,
 0.766,
 2.657,
 0.741,
 0.717,
 0.717,
 0.0,
 0.452,
 0.242,
 0.699,
 0.694,
 0.697,
 0.484,
 0.461,
 0.496,
 0.697,
 0.39,
 0.44,
 0.831,
 3.13,
 0.0,
 0.0,
 2.575,
 1.315,
 2.931,
 2.01,
 0.42,
 2.931,
 4.076,
 3.949,
 1.469,
 0.383,
 0.413,
 2.66,
 2.521,
 0.708,
 1.612,
 2.931,
 0.708,
 0.341,
 1.518,
 0.53,
 2.931,
 3.432,
 0.403,
 3.433,
 2.561,
 1.924,
 3.532,
 2.521,
 4.105,
 3.528,
 2.57,
 2.124,
 4.076,
 3.521,
 2.575,
 3.504,
 4.084,
 3.482,
 3.479,
 0.342,
 0.476,
 2.521,
 2.13,
 1.52,
 0.847,
 1.465,
 2.542,
 0.53,
 0.42,
 3.432,
 1.269,
 2.575,
 3.766,
 3.199,
 0.376,
 0.479,
 0.443,
 1.555,
 0.695,
 0.42,
 1.469,
 0.42,
 0.522,
 2.552,
 0.695,
 1.985,
 2.681,
 1.584,
 2.575,
 0.708,
 2.575,
 3.009,
 1.469,
 2.521,
 3.528,
 2.57,
 2.543,
 2.575,
 3.261,
 1.597,
 0.695,
 3.433,
 2.575,
 1.465,
 0.417,
 2.575,
 0.708,
 2.575,
 1.315,
 2.01,
 3.109,
 0.484,
 0.403,
 1.465,
 3.954,
 1.377,
 1.669,
 0.385,
 1.482,
 2.221,
 0.403,
 1.789,
 1.471,
 2.011,
 1.465,
 1.678,
 4.076,
 3.528,
 2.931,
 1.727,
 0.403,
 2.57,
 1.55,
 0.403,
 4.723,
 2.01,
 0.403,
 0.735,
 1.123,
 2.011,
 1.924,
 0.017,
 0.713,
 0.054,
 0.903,
 0.903,
 1.25,
 0.963,
 1.832,
 1.437,
 0.289,
 0.713,
 2.44,
 1.758,
 4.301,
 3.298,
 0.6,
 3.828,
 2.75,
 7.59,
 0.624,
 2.791,
 3.428,
 2.39,
 7.424,
 1.876,
 0.262,
 0.26,
 0.019,
 0.017,
 3.346,
 3.746,
 1.008,
 1.808,
 0.845,
 1.977,
 3.322,
 4.985,
 0.581,
 0.031,
 0.581,
 0.646,
 0.581,
 0.581,
 0.646,
 0.581,
 0.682,
 0.35,
 0.386,
 0.317,
 0.581,
 0.452,
 0.674,
 0.264,
 0.264,
 0.0,
 0.0,
 0.128,
 0.715,
 0.684,
 0.0,
 0.0,
 0.0,
 1.343,
 0.893,
 1.828,
 0.241,
 0.893,
 1.099,
 0.64,
 1.497,
 0.905,
 0.268,
 0.885,
 1.387,
 0.897,
 0.107,
 0.058,
 0.913,
 1.112,
 0.068,
 0.0,
 0.0,
 0.53,
 1.642,
 0.203,
 2.993,
 0.669,
 1.646,
 2.186,
 1.287,
 2.624,
 2.624,
 0.0,
 0.244,
 0.049,
 0.632,
 0.438,
 0.0,
 0.578,
 0.729,
 1.307,
 12.569,
 1.641,
 5.281,
 6.085,
 12.561,
 8.183,
 2.805,
 10.331,
 11.099,
 12.0,
 14.059,
 14.064,
 26.023,
 5.787,
 4.881,
 0.197,
 0.394,
 0.197,
 0.0,
 0.255,
 0.014,
 0.252,
 0.255,
 0.233,
 0.014,
 0.0,
 0.0,
 2.469,
 5.814,
 2.469,
 5.696,
 5.696,
 0.553,
 1.141,
 0.315,
 0.184,
 1.243,
 2.469,
 5.429,
 0.315,
 4.235,
 0.315,
 0.315,
 5.944,
 0.315,
 2.434,
 0.315,
 5.696,
 5.932,
 0.315,
 2.469,
 0.268,
 1.639,
 5.937,
 2.469,
 5.696,
 2.469,
 0.315,
 2.469,
 2.469,
 6.479,
 0.238,
 0.276,
 0.494,
 0.83,
 0.64,
 0.818,
 0.135,
 0.015,
 0.858,
 0.135,
 0.695,
 0.098,
 0.135,
 0.135,
 0.858,
 0.135,
 0.135,
 0.135,
 0.135,
 0.787,
 0.135,
 0.888,
 0.379,
 0.023,
 0.172,
 0.194,
 0.391,
 0.392,
 0.391,
 0.978,
 0.391,
 0.391,
 0.978,
 0.854,
 0.854,
 2.073,
 0.349,
 0.854,
 0.854,
 0.854,
 0.854,
 2.719,
 2.829,
 2.057,
 2.584,
 0.854,
 0.854,
 0.124,
 0.854,
 1.513,
 1.028,
 0.567,
 2.067,
 1.294,
 0.483,
 0.0,
 11.809,
 22.904,
 6.452,
 9.377,
 11.185,
 9.388,
 19.18,
 13.64,
 8.159,
 9.385,
 9.517,
 3.155,
 4.138,
 3.285,
 18.863,
 0.0,
 0.275,
 1.019,
 0.275,
 0.217,
 0.252,
 7.593,
 7.782,
 12.719,
 5.103,
 7.867,
 6.923,
 3.397,
 0.0,
 1.279,
 0.127,
 0.01,
 1.362,
 2.74,
 0.025,
 0.002,
 0.111,
 0.503,
 0.809,
 0.841,
 0.503,
 1.46,
 0.731,
 0.164,
 2.119,
 1.43,
 2.119,
 1.371,
 1.344,
 1.225,
 2.043,
 2.088,
 2.521,
 2.14,
 2.97,
 0.28,
 1.214,
 1.43,
 0.579,
 0.28,
 0.311,
 1.361,
 1.476,
 1.855,
 1.581,
 1.393,
 0.709,
 4.011,
 2.696,
 0.898,
 0.311,
 0.073,
 0.059,
 0.437,
 0.095,
 0.061,
 0.143,
 0.137,
 0.065,
 0.096,
 0.091,
 0.133,
 0.017,
 0.017,
 0.05,
 0.017,
 0.0,
 9.71,
 15.346,
 22.555,
 18.344,
 14.496,
 22.673,
 14.496,
 14.496,
 14.412,
 13.787,
 16.028,
 16.572,
 14.808,
 14.459,
 11.688,
 11.688,
 13.457,
 16.405,
 16.773,
 15.043,
 0.0,
 0.0,
 0.682,
 1.023,
 1.023,
 0.682,
 0.682,
 0.0,
 0.973,
 1.077,
 0.742,
 0.239,
 1.353,
 1.191,
 1.437,
 0.34,
 0.041,
 1.437,
 0.642,
 1.358,
 0.173,
 2.49,
 0.742,
 0.084,
 1.299,
 0.086,
 0.742,
 0.444,
 1.435,
 0.258,
 0.637,
 1.437,
 1.381,
 0.973,
 2.32,
 0.142,
 7.791,
 23.97,
 13.457,
 14.744,
 8.164,
 22.331,
 6.674,
 19.489,
 7.992,
 28.266,
 6.683,
 17.492,
 0.398,
 1.469,
 0.935,
 0.08,
 1.196,
 0.534,
 0.406,
 1.428,
 1.729,
 0.386,
 0.534,
 1.816,
 1.771,
 1.782,
 1.79,
 0.398,
 1.065,
 0.935,
 2.279,
 1.791,
 1.196,
 0.799,
 1.062,
 1.062,
 0.803,
 1.935,
 2.279,
 0.799,
 0.534,
 2.777,
 0.098,
 0.398,
 ...]

In [36]:
addingStuff['CentDist'] = CentDist

In [22]:
a = addingStuff[addingStuff['CentDist'] > 20]

In [38]:
a = addingStuff[addingStuff['Postcode No'] == 3351]
a[a['ROAD'] == 'GLENELG HIGHWAY'].sort_values(by='CentDist')

,X_x,Y_x,ROAD,Postcode No,ACCIDENT_NO_x,X_y,Y_y,ACCIDENT_NO_y,CentDist
3717,143.596129,-37.676273,GLENELG HIGHWAY,3351,T20170008280,143.45578,-37.661034,28,12.469
3713,143.596310,-37.676310,GLENELG HIGHWAY,3351,T20170004483,143.45578,-37.661034,28,12.485
3705,143.598010,-37.677177,GLENELG HIGHWAY,3351,T20150021065,143.45578,-37.661034,28,12.647
3723,143.619114,-37.681011,GLENELG HIGHWAY,3351,T20180024488,143.45578,-37.661034,28,14.546
3724,143.631620,-37.680643,GLENELG HIGHWAY,3351,T20180014434,143.45578,-37.661034,28,15.629
3712,143.637919,-37.679077,GLENELG HIGHWAY,3351,T20170000317,143.45578,-37.661034,28,16.156
3721,143.654167,-37.668894,GLENELG HIGHWAY,3351,T20190004262,143.45578,-37.661034,28,17.484
3710,143.661619,-37.658290,GLENELG HIGHWAY,3351,T20170001964,143.45578,-37.661034,28,18.122
3720,143.661944,-37.657958,GLENELG HIGHWAY,3351,T20180007390,143.45578,-37.661034,28,18.151
3711,143.666862,-37.653814,GLENELG HIGHWAY,3351,T20170001662,143.45578,-37.661034,28,18.599
3722,143.674189,-37.650588,GLENELG HIGHWAY,3351,T20180010222,143.45578,-37.661034,28,19.262
3701,143.694007,-37.635578,GLENELG HIGHWAY,3351,T20140008915,143.45578,-37.661034,28,21.164
3702,143.696111,-37.633240,GLENELG HIGHWAY,3351,T20140009046,143.45578,-37.661034,28,21.384
3709,143.714285,-37.616446,GLENELG HIGHWAY,3351,T20160019320,143.45578,-37.661034,28,23.296
3699,143.730761,-37.610673,GLENELG HIGHWAY,3351,T20130020074,143.45578,-37.661034,28,24.853
3725,143.736488,-37.609682,GLENELG HIGHWAY,3351,T20190003816,143.45578,-37.661034,28,25.369
3715,143.739989,-37.608886,GLENELG HIGHWAY,3351,T20170010941,143.45578,-37.661034,28,25.690
3707,143.765020,-37.599500,GLENELG HIGHWAY,3351,T20150024771,143.45578,-37.661034,28,28.079
3719,143.768574,-37.596759,GLENELG HIGHWAY,3351,T20170022981,143.45578,-37.661034,28,28.458
3708,143.104989,-37.689012,GLENELG HIGHWAY,3351,T20160014658,143.45578,-37.661034,28,31.029
3714,143.075794,-37.683101,GLENELG HIGHWAY,3351,T20170003088,143.45578,-37.661034,28,33.534
3718,143.075794,-37.683101,GLENELG HIGHWAY,3351,T20160023019,143.45578,-37.661034,28,33.534
3704,143.075794,-37.683101,GLENELG HIGHWAY,3351,T20150019699,143.45578,-37.661034,28,33.534
3703,143.075794,-37.683101,GLENELG HIGHWAY,3351,T20150017356,143.45578,-37.661034,28,33.534
3700,143.000251,-37.692938,GLENELG HIGHWAY,3351,T20140007167,143.45578,-37.661034,28,40.246
3716,142.887908,-37.696525,GLENELG HIGHWAY,3351,T20170003168,143.45578,-37.661034,28,50.131
3698,142.839833,-37.712514,GLENELG HIGHWAY,3351,T20130023639,143.45578,-37.661034,28,54.502
3706,142.782550,-37.714749,GLENELG HIGHWAY,3351,T20150022409,143.45578,-37.661034,28,59.541

In [24]:
for gname, group in newAdding.groupby(['Postcode No','ROAD','X_y','Y_y']):

SyntaxError: unexpected EOF while parsing (<ipython-input-24-f0da0dd90e36>, line 2)